/**
 * Word list for generated temporary passwords.
 *
 * These passwords get read out over the phone, so what is excluded matters more
 * than the count. Every word here is common, spelled the way it sounds, and
 * unambiguous when spoken. The list is mechanically checked to contain no
 * homophones, no anagram pairs (angel/angle, lemon/melon) and no pairs one letter
 * apart (locket/rocket/socket, coach/couch) — that check pruned it from 810 words
 * down to 741.
 *
 * If you add a word, re-run that check: no entry may be within one edit, or an
 * anagram, of any other entry.
 */
export const PASSWORD_WORDS = [
    'able', 'acid', 'acorn', 'album', 'alert', 'alley', 'anchor', 'angel', 'ankle', 'apple',
    'april', 'apron', 'arena', 'armor', 'arrow', 'artist', 'aspen', 'atlas', 'attic', 'audio',
    'autumn', 'avenue', 'awake', 'award', 'bacon', 'badge', 'bagel', 'baker', 'balance', 'balloon',
    'bamboo', 'banana', 'bandit', 'banjo', 'barley', 'barrel', 'basil', 'basket', 'beaver', 'bench',
    'bicycle', 'bingo', 'birch', 'biscuit', 'bishop', 'bison', 'black', 'blanket', 'blend', 'blink',
    'blossom', 'blue', 'bobcat', 'bolt', 'bonus', 'book', 'border', 'bottle', 'boulder', 'bounce',
    'boxer', 'brave', 'bread', 'brick', 'bright', 'bronze', 'broom', 'brown', 'brush', 'bubble',
    'bucket', 'buffalo', 'bugle', 'bulb', 'bundle', 'bunny', 'burger', 'butter', 'button', 'cabin',
    'cactus', 'camel', 'camera', 'canvas', 'canyon', 'cargo', 'carpet', 'cattle', 'cedar', 'celery',
    'cement', 'chair', 'chalk', 'charm', 'cheese', 'cherry', 'chest', 'chicken', 'chili', 'chimney',
    'chip', 'chorus', 'cider', 'cinema', 'circle', 'circus', 'city', 'classic', 'clay', 'clever',
    'cliff', 'clock', 'closet', 'cloud', 'clown', 'club', 'cobra', 'cocoa', 'coin', 'collar',
    'colony', 'color', 'column', 'comet', 'comic', 'compass', 'cookie', 'copper', 'coral', 'corner',
    'cottage', 'cotton', 'couch', 'county', 'cousin', 'cover', 'cowboy', 'coyote', 'crab', 'cradle',
    'crane', 'crayon', 'cricket', 'crimson', 'crispy', 'crystal', 'cube', 'cuckoo', 'cupcake', 'curtain',
    'cushion', 'cymbal', 'daisy', 'dancer', 'dandy', 'dawn', 'decoy', 'deer', 'denim', 'dentist',
    'desert', 'design', 'desk', 'diamond', 'diary', 'dinner', 'dolphin', 'domino', 'donut', 'double',
    'dragon', 'drama', 'dream', 'dress', 'drift', 'drum', 'duck', 'dune', 'dusty', 'eagle',
    'easel', 'echo', 'eclipse', 'elbow', 'elder', 'electric', 'elephant', 'elm', 'ember', 'emerald',
    'empire', 'energy', 'engine', 'envelope', 'equal', 'eraser', 'escape', 'estate', 'evening', 'exit',
    'expert', 'fabric', 'falcon', 'fancy', 'farmer', 'fence', 'fern', 'ferry', 'festival', 'fiber',
    'fiddle', 'field', 'fig', 'filter', 'finch', 'fire', 'fish', 'flag', 'flask', 'flint',
    'floral', 'flute', 'foam', 'folder', 'forest', 'fork', 'fortune', 'fossil', 'fox', 'frame',
    'freckle', 'friend', 'frog', 'frost', 'fudge', 'galaxy', 'gallery', 'garlic', 'gate', 'gecko',
    'gem', 'gentle', 'geyser', 'giant', 'ginger', 'giraffe', 'glacier', 'glider', 'glove', 'golden',
    'goose', 'gorilla', 'granite', 'grape', 'grass', 'green', 'grill', 'guitar', 'gulf', 'hammer',
    'hamster', 'handle', 'harbor', 'harvest', 'hazel', 'heart', 'hedge', 'helmet', 'herbal', 'hickory',
    'hollow', 'honey', 'hoodie', 'horizon', 'hornet', 'horse', 'hotel', 'hunter', 'husky', 'ice',
    'igloo', 'index', 'indigo', 'ink', 'insect', 'iron', 'island', 'ivory', 'ivy', 'jacket',
    'jade', 'jaguar', 'jam', 'jasmine', 'jet', 'jewel', 'jigsaw', 'jockey', 'jolly', 'journal',
    'jubilee', 'juice', 'jumbo', 'jungle', 'juniper', 'jupiter', 'kayak', 'kettle', 'keyboard', 'kitchen',
    'kite', 'kiwi', 'koala', 'ladder', 'lagoon', 'lake', 'lamp', 'lantern', 'laptop', 'lasso',
    'lattice', 'laundry', 'lava', 'lavender', 'leopard', 'letter', 'lettuce', 'level', 'library', 'license',
    'lily', 'lime', 'linen', 'lion', 'lizard', 'llama', 'lobby', 'lobster', 'log', 'lotus',
    'lounge', 'lucky', 'lumber', 'lunar', 'lyric', 'magnet', 'magnolia', 'mahogany', 'mailbox', 'mango',
    'mantis', 'maple', 'marble', 'margin', 'marina', 'market', 'marmalade', 'mascot', 'mask', 'meadow',
    'medal', 'melody', 'melon', 'mercury', 'mermaid', 'mesa', 'meteor', 'method', 'midnight', 'mineral',
    'mint', 'mirror', 'mitten', 'mixer', 'model', 'module', 'moment', 'monarch', 'monkey', 'monsoon',
    'month', 'moon', 'moss', 'motor', 'mountain', 'mulberry', 'museum', 'mushroom', 'music', 'mustard',
    'napkin', 'nature', 'navy', 'nebula', 'necklace', 'nectar', 'needle', 'neon', 'nest', 'network',
    'nickel', 'noble', 'noodle', 'north', 'notebook', 'nova', 'novel', 'nugget', 'nutmeg', 'oasis',
    'oatmeal', 'ocean', 'octopus', 'office', 'olive', 'omelet', 'onion', 'opal', 'orange', 'orbit',
    'orchard', 'orchid', 'organ', 'origami', 'oriole', 'ostrich', 'otter', 'outlet', 'oven', 'owl',
    'oxford', 'oxygen', 'oyster', 'pack', 'palace', 'pancake', 'panda', 'papaya', 'paper', 'paprika',
    'parade', 'parcel', 'parrot', 'parsley', 'pasta', 'pastel', 'pastry', 'pattern', 'peach', 'peacock',
    'peanut', 'pearl', 'pebble', 'pelican', 'pencil', 'pendant', 'penguin', 'pepper', 'petal', 'pewter',
    'phantom', 'phoenix', 'photo', 'piano', 'picnic', 'pigeon', 'pilot', 'pine', 'pistol', 'pitcher',
    'pixel', 'pizza', 'planet', 'plank', 'plasma', 'plateau', 'platinum', 'plaza', 'plum', 'poem',
    'pollen', 'pony', 'poplar', 'poppy', 'postal', 'potato', 'pottery', 'powder', 'prairie', 'pretzel',
    'primrose', 'prism', 'prize', 'public', 'pudding', 'puffin', 'pumpkin', 'puppet', 'purple', 'puzzle',
    'pyramid', 'python', 'quail', 'quarry', 'quartz', 'quilt', 'quiver', 'rabbit', 'raccoon', 'radar',
    'radish', 'rafter', 'rainbow', 'ranch', 'raven', 'ravine', 'razor', 'record', 'redwood', 'reef',
    'reindeer', 'reptile', 'ribbon', 'ridge', 'rifle', 'river', 'roast', 'robin', 'robot', 'rodeo',
    'roof', 'rooster', 'rope', 'rosemary', 'ruby', 'rudder', 'runner', 'saddle', 'safari', 'saffron',
    'salad', 'salmon', 'salsa', 'sample', 'sandal', 'sapphire', 'satellite', 'satin', 'sauce', 'sausage',
    'scarf', 'school', 'scooter', 'scorpion', 'scout', 'sculpture', 'seagull', 'seal', 'season', 'seaweed',
    'sector', 'sequoia', 'server', 'shadow', 'shampoo', 'shark', 'shelf', 'shelter', 'sherbet', 'shingle',
    'shovel', 'shrimp', 'shuttle', 'signal', 'silver', 'siren', 'sketch', 'ski', 'skillet', 'skyline',
    'sleigh', 'slipper', 'slogan', 'smoke', 'snapper', 'snorkel', 'snow', 'socket', 'sofa', 'solar',
    'sonnet', 'soup', 'south', 'soybean', 'spaniel', 'sparrow', 'spatula', 'sphere', 'spider', 'spinach',
    'spiral', 'sponge', 'spoon', 'sprout', 'squash', 'squid', 'squirrel', 'stadium', 'stallion', 'stapler',
    'starfish', 'station', 'statue', 'stereo', 'stingray', 'storm', 'stove', 'strawberry', 'stream', 'string',
    'studio', 'sugar', 'suitcase', 'summit', 'sunflower', 'sunset', 'surfer', 'swamp', 'sweater', 'swordfish',
    'symbol', 'syrup', 'tablet', 'taco', 'tadpole', 'tailor', 'tambourine', 'tangerine', 'tapioca', 'tavern',
    'teapot', 'telescope', 'temple', 'tender', 'tennis', 'tent', 'terrace', 'thermal', 'thimble', 'thistle',
    'thunder', 'ticket', 'tiger', 'timber', 'toaster', 'toffee', 'tomato', 'topaz', 'torch', 'tornado',
    'tortoise', 'toucan', 'tower', 'tractor', 'trailer', 'trapeze', 'travel', 'treasure', 'trellis', 'triangle',
    'trident', 'trophy', 'tropic', 'trout', 'trumpet', 'tulip', 'tundra', 'tunnel', 'turban', 'turkey',
    'turnip', 'turtle', 'tuxedo', 'ukulele', 'umbrella', 'unicorn', 'uniform', 'upgrade', 'uptown', 'valve',
    'vanilla', 'vault', 'velvet', 'vendor', 'venus', 'vessel', 'victory', 'video', 'village', 'vinegar',
    'vineyard', 'violet', 'violin', 'volcano', 'voltage', 'voyage', 'waffle', 'wagon', 'walnut', 'walrus',
    'warden', 'wasabi', 'watch', 'water', 'weather', 'welcome', 'whale', 'wheat', 'whisker', 'willow',
    'window', 'winter', 'wisdom', 'wolf', 'wombat', 'wonder', 'wooden', 'workshop', 'world', 'wreath',
    'yacht', 'yarn', 'yellow', 'yogurt', 'zebra', 'zephyr', 'zigzag', 'zinnia', 'zipper', 'zodiac',
    'zucchini',
]
